name: Continuous Deployment
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn global add patch-package
      - run: yarn install
      - run: yarn test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup nodejs 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn global add patch-package
      - run: yarn install
      - run: yarn lint
      - run: terraform fmt -check -recursive
